#!/usr/bin/env bash
## LOCATION: $HOME/.bin/

notify() {
	notify-send "$@" || { echo "$@"; }
}
download_wp() {
	wget -O /tmp/wallpaper.jpg https://unsplash.it/2650/1440/?random || { notify 'Download failed. Check network status'; exit 1; }
	wp="/tmp/wallpaper.jpg"
}
update_bar() {
	pkill lemonbar
	sleep 1
	$HOME/.bin/bar_update.sh
}
usage() {
    echo "Usage:"
    echo "new             new dark wallpaper and theme"
    echo "new [*]         new light wallpaper and theme"
    echo "set \$PATH       set theme with existing wallpaper"
    echo "set \$PATH [*]   set light theme with existing wallpaper"
    echo "copy [name]      copy new wallpaper to Pictures folder"
}

case $1 in
	set) [[ -z "$3" ]] && mode="-i" || mode="-l -i"
		wal $mode $2
		sleep 2
		update_bar
		notify "Theme updated" ;;
	new) [[ -z "$2" ]] && mode="-i" || mode="-l -i"
		wal -c
		download_wp
		sleep 2
		wal $mode $wp
		sleep 2
		update_bar
		notify "Theme updated" ;;
	copy) cp /tmp/wallpaper.jpg $HOME/Pictures/$2.jpg ;;
	*) usage ;;
esac

