#!/usr/bin/env bash
## LOCATION: $HOME/.bin/

notify() {
	notify-send "$@" || { echo "$@"; }
}
download_wp() {
	echo "Downloading wallpaper.."
	wget -q -O /tmp/wallpaper.jpg https://unsplash.it/2650/1440/?random || { notify 'Download failed. Check network status'; exit 1; }
	wp="/tmp/wallpaper.jpg"
}
update_bar() {
	sleep 2
	pkill lemonbar
	sleep 1
	$HOME/.bin/bar_update.sh
}
update_dunst() {
	ln -sf $HOME/.cache/wal/dunstrc $HOME/.config/dunst/dunstrc
	pkill dunst
	dunst &
}
list() {
	for i in ${wp[@]}; do
		echo $(basename $i | cut -f 1 -d '.')
	done
}
usage() {
    echo "Usage:"
    echo "new             new dark wallpaper and theme"
    echo "new [*]         new light wallpaper and theme"
    echo "set \$PATH       set theme with existing wallpaper"
    echo "set \$PATH [*]   set light theme with existing wallpaper"
    echo "copy [name]      copy new wallpaper to Pictures folder"
}
wp=($(find $HOME/Pictures -type f | sort -R))
wp_path="$HOME/Pictures/"
case $1 in
	set) [[ -z "$3" ]] && mode="-i" || mode="-l -i"
		[[ $2 == "random" ]] && bg=${wp[0]} || bg="$wp_path$2.jpg"
		wal $mode $bg
		update_dunst
		update_bar
		notify "Theme updated: $bg" ;;
	new) [[ -z "$2" ]] && mode="-i" || mode="-l -i"
		wal -c
		download_wp
		sleep 2
		wal $mode $wp
		update_dunst
		update_bar
		notify "Theme updated" ;;
	copy) cp /tmp/wallpaper.jpg $HOME/Pictures/$2.jpg ;;
	list) list ;;
	*) usage ;;
esac
