#!/usr/bin/env bash

[[ $(cat /etc/issue) == *"Ubuntu"* ]] || { echo "This install script is built for debian-based OS that uses apt package manager. Please modify the script for it to work on a(n) $(cat /etc/issue | awk '{print $1}') system."; exit 1; }

declare -a REPOS=(kaugm/mmwm dylanaraps/fff kaugm/sxiv vinceliuice/Qogir-theme vinceliuice/Qogir-icon-theme drscream/lemonbar-xft)
packages="
xinit
rxvt-unicode
git
vim
build-essential
x11-utils
x11-xserver-utils
xorg
feh
libimlib2
xrdp
rofi
libxcb-util-dev
libxcb-icccm4-dev
libxcb-keysyms1-dev
libxcb-ewmh-dev
pkg-config
mousepad
firefox
gimp
thunar
ranger
lightdm
python3.6
python3-pip
htop
scrot
libimlib2-dev
libexif-dev
libxft-dev
lxappearance
libxcb-randr0-dev #lemonbar-xft
libx11-xcb-dev #lemonbar-xft
libxcb-xinerama0-dev #lemonbar-xft
notify-send
dunst"

pkg_install() {
	sudo apt-get update
	sudo apt install $packages
}
repo_clone() {
	for REPO in ${REPOS[@]}; do
		git clone https://github.com/$REPO
	done
}
pip_install() {
	pip3 install pywal
}

main() {
	pkg_install
	sleep 5
	repo_clone
	sleep 5
	pip_install
	sleep 5
	echo "Please dont forget to compile ${REPOS[@]}."
	echo "Please dont forget to install VS Code."
}

main "$@"
