#!/usr/bin/env bash
## LOCATION: $HOME/.fvwm/scripts/

if [ ! -f ~/.fvwm/dyn_colors.fvwm2rc ]; then
	touch ~/.fvwm/dyn_colors.fvwm2rc
fi
	
download_theme_light() {
	wal -c
	wget -O /tmp/wallpaper.jpg https://unsplash.it/2650/1440/?$3 || { notify 'Failed. Check network status'; exit 1; }
	sleep 3
	wal -l -i /tmp/wallpaper.jpg
	feh --bg-scale /tmp/wallpaper.jpg || { notify 'Failed. Feh cant read image'; exit 1; }
	sleep 2
	export_colors
}

set_theme_light() {
	wal -l -i $3
	feh --bg-scale $3 || { notify 'Failed. Feh cant read image'; exit 1; }
	sleep 4
	export_colors
}


download_theme_dark() {
	wal -c
	wget -O /tmp/wallpaper.jpg https://unsplash.it/2650/1440/?$3 || { notify 'Failed. Check network status'; exit 1; }
	sleep 3
	wal -i /tmp/wallpaper.jpg
	feh --bg-scale /tmp/wallpaper.jpg || { notify 'Failed. Feh cant read image'; exit 1; }
	sleep 2
	export_colors
}

set_theme_dark() {
	wal -i $3
	feh --bg-scale $3 || { notify 'Failed. Feh cant read image'; exit 1; }
	sleep 4
	export_colors
}

export_colors() {
	source ~/.cache/wal/colors.sh
#	bg_color=$(cat ~/.cache/wal/colors | sed '1q;d')
#	fg_color=$(cat ~/.cache/wal/colors | sed '7q;d')
#	hi_color=$(cat ~/.cache/wal/colors | sed '5q;d')
	bg_color=$color0
	fg_color=$color7
	hi_color=$color3
	echo "Colorset 5 fg $fg_color, bg $bg_color, hi, sh, Plain, NoShape" > ~/.fvwm/dyn_colors.fvwm2rc
	echo "Colorset 6 fg $bg_color, bg $fg_color, hi, sh, Plain, NoShape" >> ~/.fvwm/dyn_colors.fvwm2rc
	echo "SetEnv active_fg $hi_color" >> ~/.fvwm/dyn_colors.fvwm2rc
	sleep 1
	fvwm -replace &
}

notify() {
	notify-send "$@"
	echo "$@"
}

case $1 in
	download)
		case $2 in
			light) download_theme_light "$@" ;;
			dark) download_theme_dark "$@" ;;
		esac
	;;
	set) 
		case $2 in
			light) set_theme_light "$@" ;;
			dark) set_theme_dark "$@" ;;
		esac
	;;
	copy)
		cp /tmp/wallpaper.jpg $HOME/Pictures/$2.jpg ;;
	*) echo "1. ./theme [download/set] [light/dark] [category/random] {image} << for [set] option only"
	echo "2. ./theme [copy] {image_name} (no .jpg at end of filename)"
	;;
esac






