#!/usr/bin/env bash
## LOCATION: $HOME/.fvwm/scripts/
	
download_theme_light() {
	wal -c
	wget -O /tmp/wallpaper.jpg https://unsplash.it/2650/1440/?$3 || { notify 'Failed. Check network status'; exit 1; }
	sleep 3
	wal -l -i /tmp/wallpaper.jpg
	feh --bg-scale /tmp/wallpaper.jpg || { notify 'Failed. Feh cant read image'; exit 1; }
	sleep 2
}

set_theme_light() {
	wal -l -i $HOME/Pictures/$3
	feh --bg-scale $HOME/Pictures/$3 || { notify 'Failed. Feh cant read image'; exit 1; }
	sleep 4
}


download_theme_dark() {
	wal -c
	wget -O /tmp/wallpaper.jpg https://unsplash.it/2650/1440/?$3 || { notify 'Failed. Check network status'; exit 1; }
	sleep 3
	wal -i /tmp/wallpaper.jpg
	feh --bg-scale /tmp/wallpaper.jpg || { notify 'Failed. Feh cant read image'; exit 1; }
	sleep 2
}

set_theme_dark() {
	wal -i $HOME/Pictures/$3
	feh --bg-scale $HOME/Pictures/$3 || { notify 'Failed. Feh cant read image'; exit 1; }
	sleep 4
}


notify() {
	notify-send "$@"
	echo "$@"
}

case $1 in
	download)
		case $2 in
			light) download_theme_light "$@" ;;
			dark) download_theme_dark "$@" ;;
		esac
	;;
	set) 
		case $2 in
			light) set_theme_light "$@" ;;
			dark) set_theme_dark "$@" ;;
		esac
	;;
	copy)
		cp /tmp/wallpaper.jpg $HOME/Pictures/$2.jpg ;;
	*) echo "1. ./theme [download/set] [light/dark] [category/random] {image} << for [set] option only"
	echo "2. ./theme [copy] {image_name} (no .jpg at end of filename)"
	;;
esac






